### ISSUE TITLE
crash on project build/rebuild on latest master

### ISSUE THREAD

**Issue by sss123next** [eranif/codelite#2399]
```
Thread 29 received signal SIGSEGV, Segmentation fault.
[Switching to LWP 100227 of process 43368]
0x0000000000555a40 in wxString::~wxString() ()
(gdb) where
#0  0x0000000000555a40 in wxString::~wxString() ()
#1  0x0000000805e55b16 in FileUtils::WildMatch(wxArrayString const&, wxString const&) () at /usr/local/lib/codelite/liblibcodelite.so
#2  0x0000000805de56bd in clFilesScanner::Scan(wxString const&, std::__1::vector<wxString, std::__1::allocator<wxString> >&, wxString const&, wxString const&, std::__1::unordered_set<wxString, std::__1::hash<wxString>, std::__1::equal_to<wxString>, std::__1::allocator<wxString> > const&) () at /usr/local/lib/codelite/liblibcodelite.so
#3  0x000000080543887f in  () at /usr/local/lib/codelite/libplugin.so
#4  0x0000000804b01776 in thread_start (curthread=0x80ac42500) at /usr/src/lib/libthr/thread/thr_create.c:292
#5  0x0000000000000000 in  ()

```

**Comment by sss123next** [comment]
```
Thread 1 "codelite" received signal SIGSEGV, Segmentation fault.
0x00007ffff4a0a913 in pango_font_map_get_serial () from /usr/x86_64-pc-linux-gnu/lib/libpango-1.0.so.0
(gdb) where
#0  0x00007ffff4a0a913 in pango_font_map_get_serial () at /usr/x86_64-pc-linux-gnu/lib/libpango-1.0.so.0
#1  0x00007ffff4a0801a in pango_context_get_serial () at /usr/x86_64-pc-linux-gnu/lib/libpango-1.0.so.0
#2  0x00007ffff4a0fb5e in pango_layout_new () at /usr/x86_64-pc-linux-gnu/lib/libpango-1.0.so.0
#3  0x00007ffff6cd7048 in wxWindowDCImpl::wxWindowDCImpl(wxDC*, wxWindow*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk2u_core-3.1.so.3
#4  0x00007ffff6daba15 in wxNativeDCFactory::CreateWindowDC(wxWindowDC*, wxWindow*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk2u_core-3.1.so.3
#5  0x00007ffff6dad9f0 in wxWindowDC::wxWindowDC(wxWindow*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk2u_core-3.1.so.3
#6  0x00007ffff6ccee34 in wxWindow::GTKSendPaintEvents(_GdkRegion const*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk2u_core-3.1.so.3
#7  0x00007ffff6ccf14c in expose_event () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk2u_core-3.1.so.3
#8  0x00007ffff7c1bf1b in _gtk_marshal_BOOLEAN__BOXED () at /usr/x86_64-pc-linux-gnu/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff49975ca in <emit signal ??? on instance 0x55555718d2b0 [wxPizza]> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../glib-scm/gobject/gsignal.c:3479
    #9  0x00007ffff497a0c3 in g_closure_invoke (closure=0x5555571989b0, return_value=0x7fffffffd200, n_param_values=2, param_values=0x7fffffffd2c0, invocation_hint=0x7fffffffd250) at ../glib-scm/gobject/gclosure.c:810
    #10 0x00007ffff498d928 in signal_emit_unlocked_R (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x55555718d2b0, emission_return=emission_return@entry=0x7fffffffd3b0, instance_and_params=instance_and_params@entry=0x7fffffffd2c0)
    at ../glib-scm/gobject/gsignal.c:3667
    #11 0x00007ffff4996733 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd468) at ../glib-scm/gobject/gsignal.c:3433
#13 0x00007ffff7d7949c in gtk_widget_event_internal () at /usr/x86_64-pc-linux-gnu/lib/libgtk-x11-2.0.so.0
#14 0x00007ffff7c1a800 in gtk_main_do_event () at /usr/x86_64-pc-linux-gnu/lib/libgtk-x11-2.0.so.0
#15 0x00007ffff5333b6f in _gdk_window_process_updates_recurse.localalias.102 () at /usr/x86_64-pc-linux-gnu/lib/libgdk-x11-2.0.so.0
#16 0x00007ffff5333b15 in _gdk_window_process_updates_recurse.localalias.102 () at /usr/x86_64-pc-linux-gnu/lib/libgdk-x11-2.0.so.0
#17 0x00007ffff5333b15 in _gdk_window_process_updates_recurse.localalias.102 () at /usr/x86_64-pc-linux-gnu/lib/libgdk-x11-2.0.so.0
#18 0x00007ffff532f9e4 in gdk_window_process_updates_internal.part () at /usr/x86_64-pc-linux-gnu/lib/libgdk-x11-2.0.so.0
#19 0x00007ffff5330464 in gdk_window_process_all_updates () at /usr/x86_64-pc-linux-gnu/lib/libgdk-x11-2.0.so.0
#20 0x00007ffff53304b9 in gdk_window_update_idle () at /usr/x86_64-pc-linux-gnu/lib/libgdk-x11-2.0.so.0
#21 0x00007ffff52fd8c4 in gdk_threads_dispatch () at /usr/x86_64-pc-linux-gnu/lib/libgdk-x11-2.0.so.0
#22 0x00007ffff488e3a0 in g_main_dispatch (context=0x555555f36ad0) at ../glib-scm/glib/gmain.c:3185
#23 0x00007ffff488e3a0 in g_main_context_dispatch (context=context@entry=0x555555f36ad0) at ../glib-scm/glib/gmain.c:3850
#24 0x00007ffff488e758 in g_main_context_iterate (context=0x555555f36ad0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib-scm/glib/gmain.c:3923
#25 0x00007ffff488ea12 in g_main_loop_run (loop=0x555556042280) at ../glib-scm/glib/gmain.c:4117
#26 0x00007ffff7c1909f in gtk_main () at /usr/x86_64-pc-linux-gnu/lib/libgtk-x11-2.0.so.0
#27 0x00007ffff6ca3285 in wxGUIEventLoop::DoRun() () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk2u_core-3.1.so.3
#28 0x00007ffff66cc15d in wxEventLoopBase::Run() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.3
#29 0x00007ffff66977b6 in wxAppConsoleBase::MainLoop() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.3
#30 0x00007ffff67186c5 in wxEntry(int&, wchar_t**) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.3
#31 0x0000555555866fee in main ()

```

**Comment by sss123next** [comment]
looks like it's wxGTK 3.1.3 upstream bug
