### ISSUE TITLE
crash on workspace load

### ISSUE THREAD

**Issue by sss123next** [eranif/codelite#2979]
on current master ef8c060f741d7a4cde0386baf9cc9611d79f725a

```
Thread 12 (Thread 0x7fe72892c640 (LWP 72974) "codelite"):
#0  0x00007fe72ea6b0fd in select () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72f046170 in clSocketBase::SelectReadMS(long) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#2  0x00007fe72f0499b5 in clSocketAsyncThread::BufferLoop(wxSharedPtr<clSocketBase>) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#3  0x00007fe72f04a3e4 in clSocketAsyncThread::ClientMain() () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#4  0x00007fe730e8b732 in wxThread::CallEntry() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#5  0x00007fe730e8bd3c in wxThreadInternal::PthreadStart(wxThread*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#6  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 11 (Thread 0x7fe709a37640 (LWP 72958) "codelite"):
#0  0x00007fe72ea6b0fd in select () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72f0960bb in UnixProcess::ReadAll(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#2  0x00007fe72f097b88 in UnixProcess::StartReaderThread()::{lambda(UnixProcess*, int, int)#1}::operator()(UnixProcess*, int, int) const [clone .constprop.0] () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#3  0x00007fe72ed2add4 in execute_native_thread_routine () at /usr/x86_64-pc-linux-gnu/lib/libstdc++.so.6
#4  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#5  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 10 (Thread 0x7fe709236640 (LWP 72957) "codelite"):
#0  0x00007fe72e9ebe96 in __futex_abstimed_wait_common () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72e9eea94 in pthread_cond_timedwait () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x00007fe730e825bb in wxConditionInternal::WaitTimeout(unsigned long) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#3  0x00007fe72f0984ae in wxMessageQueue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::ReceiveTimeout(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#4  0x00007fe72f096a72 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<UnixProcess::StartWriterThread()::{lambda(UnixProcess*, int)#1}, UnixProcess*, int> > >::_M_run() () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#5  0x00007fe72ed2add4 in execute_native_thread_routine () at /usr/x86_64-pc-linux-gnu/lib/libstdc++.so.6
#6  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 9 (Thread 0x7fe729b70640 (LWP 72734) "codelite"):
#0  0x00007fe72ea6b0fd in select () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72f0960bb in UnixProcess::ReadAll(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#2  0x00007fe72f097d90 in UnixProcess::StartReaderThread()::{lambda(UnixProcess*, int, int)#1}::operator()(UnixProcess*, int, int) const [clone .constprop.0] () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#3  0x00007fe72ed2add4 in execute_native_thread_routine () at /usr/x86_64-pc-linux-gnu/lib/libstdc++.so.6
#4  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#5  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 8 (Thread 0x7fe70a6e5640 (LWP 72733) "codelite"):
#0  0x00007fe72e9ebe96 in __futex_abstimed_wait_common () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72e9eea94 in pthread_cond_timedwait () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x00007fe730e825bb in wxConditionInternal::WaitTimeout(unsigned long) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#3  0x00007fe72f0984ae in wxMessageQueue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::ReceiveTimeout(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#4  0x00007fe72f096a72 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<UnixProcess::StartWriterThread()::{lambda(UnixProcess*, int)#1}, UnixProcess*, int> > >::_M_run() () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#5  0x00007fe72ed2add4 in execute_native_thread_routine () at /usr/x86_64-pc-linux-gnu/lib/libstdc++.so.6
#6  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 7 (Thread 0x7fe72c7d1640 (LWP 72720) "codelite"):
#0  0x00007fe72ea3b06a in clock_nanosleep () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72ea3fd97 in nanosleep () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x00007fe730e9021c in wxMicroSleep(unsigned long) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#3  0x00007fe72f09bb3e in ZombieReaperPOSIX::Entry() () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#4  0x00007fe730e8b732 in wxThread::CallEntry() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#5  0x00007fe730e8bd3c in wxThreadInternal::PthreadStart(wxThread*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#6  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 6 (Thread 0x7fe70b7a0640 (LWP 72715) "codelite"):
#0  0x00007fe72e9ebe96 in __futex_abstimed_wait_common () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72e9ee79f in pthread_cond_wait () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x00007fe72ed253f0 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /usr/x86_64-pc-linux-gnu/lib/libstdc++.so.6
#3  0x00007fe72f1a471b in WorkerThread::Entry() () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#4  0x00007fe730e8b732 in wxThread::CallEntry() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#5  0x00007fe730e8bd3c in wxThreadInternal::PthreadStart(wxThread*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#6  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 5 (Thread 0x7fe70af22640 (LWP 72709) "codelite"):
#0  0x00007fe72ea6b0fd in select () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72f045dfd in clSocketBase::SelectRead(long) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#2  0x00007fe72f04b442 in clSocketServer::WaitForNewConnectionRaw(long) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#3  0x00007fe72f04b4c5 in clSocketServer::WaitForNewConnection(long) () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#4  0x000055b3821ca8ce in clSingleInstanceThread::Entry() ()
#5  0x00007fe730e8b732 in wxThread::CallEntry() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#6  0x00007fe730e8bd3c in wxThreadInternal::PthreadStart(wxThread*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#7  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#8  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 4 (Thread 0x7fe72bb0c640 (LWP 72708) "codelite"):
#0  0x00007fe72e9ebe96 in __futex_abstimed_wait_common () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72e9ee79f in pthread_cond_wait () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x00007fe72ed253f0 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /usr/x86_64-pc-linux-gnu/lib/libstdc++.so.6
#3  0x00007fe72f1a471b in WorkerThread::Entry() () at /usr/x86_64-pc-linux-gnu/lib/codelite/liblibcodelite.so
#4  0x00007fe730e8b732 in wxThread::CallEntry() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#5  0x00007fe730e8bd3c in wxThreadInternal::PthreadStart(wxThread*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#6  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 3 (Thread 0x7fe7291ad640 (LWP 72638) "pool-codelite"):
#0  0x00007fe72ea6e0dd in syscall () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72de5d8b2 in g_cond_wait_until (cond=cond@entry=0x55b3845fe2f8, mutex=mutex@entry=0x55b3845fe2f0, end_time=end_time@entry=7163606387) at ../glib-2.72.0/glib/gthread-posix.c:1623
#2  0x00007fe72ddd8971 in g_async_queue_pop_intern_unlocked (queue=0x55b3845fe2f0, wait=1, end_time=7163606387) at ../glib-2.72.0/glib/gasyncqueue.c:422
#3  0x00007fe72ddd8f52 in g_async_queue_timeout_pop (queue=0x55b3845fe2f0, timeout=timeout@entry=15000000) at ../glib-2.72.0/glib/gasyncqueue.c:545
#4  0x00007fe72de34a39 in g_thread_pool_wait_for_new_pool () at ../glib-2.72.0/glib/gthreadpool.c:183
#5  g_thread_pool_thread_proxy (data=<optimized out>) at ../glib-2.72.0/glib/gthreadpool.c:411
#6  0x00007fe72de3409d in g_thread_proxy (data=0x55b3845ff0c0) at ../glib-2.72.0/glib/gthread.c:827
#7  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#8  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 2 (Thread 0x7fe72b1d1640 (LWP 72633) "gmain"):
#0  0x00007fe72ea687ff in poll () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72de0a13e in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x55b385806730, timeout=<optimized out>, context=0x55b385d867e0) at ../glib-2.72.0/glib/gmain.c:4516
#2  g_main_context_iterate (context=context@entry=0x55b385d867e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib-2.72.0/glib/gmain.c:4206
#3  0x00007fe72de0a24f in g_main_context_iteration (context=0x55b385d867e0, may_block=may_block@entry=1) at ../glib-2.72.0/glib/gmain.c:4276
#4  0x00007fe72de0a2a1 in glib_worker_main (data=<optimized out>) at ../glib-2.72.0/glib/gmain.c:6178
#5  0x00007fe72de3409d in g_thread_proxy (data=0x55b387b1a700) at ../glib-2.72.0/glib/gthread.c:827
#6  0x00007fe72e9ef3da in start_thread () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe72ea75c20 in clone3 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6

Thread 1 (Thread 0x7fe72d137c80 (LWP 72606) "codelite"):
#0  0x00007fe72ea3fb1a in wait4 () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007fe72e9aff2b in do_system () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x000055b381ed94f8 in  ()
#3  0x00007fe72e9a31f0 in <signal handler called> () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#4  0x00007fe72e9f117c in __pthread_kill_implementation () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#5  0x00007fe72e9a3146 in raise () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#6  0x00007fe72e98d7f1 in abort () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#7  0x00007fe730d52133 in wxMakeShellCommand(wxString const&) [clone .cold] () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#8  0x00007fe72e9a31f0 in <signal handler called> () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#9  0x00007fe7307d07bb in wxClientDCImpl::wxClientDCImpl(wxClientDC*, wxWindow*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk3u_core-3.1.so.5
#10 0x00007fe7308c6f40 in wxClientDC::wxClientDC(wxWindow*) () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk3u_core-3.1.so.5
#11 0x00007fe72f9105d6 in (anonymous namespace)::SetBestXButtonSize(wxWindow*) () at /usr/x86_64-pc-linux-gnu/lib/codelite/libplugin.so
#12 0x00007fe72f91113a in clTabInfo::clTabInfo(clTabCtrl*, unsigned long, wxWindow*, wxString const&, int) () at /usr/x86_64-pc-linux-gnu/lib/codelite/libplugin.so
#13 0x00007fe72f70b3d1 in clGTKNotebook::GetAllTabs(std::vector<wxSharedPtr<clTabInfo>, std::allocator<wxSharedPtr<clTabInfo> > >&) () at /usr/x86_64-pc-linux-gnu/lib/codelite/libplugin.so
#14 0x000055b3820bf1dc in MainBook::GetAllTabs(std::vector<clTab, std::allocator<clTab> >&) ()
#15 0x000055b382129728 in PluginManager::GetAllTabs(std::vector<clTab, std::allocator<clTab> >&) ()
#16 0x000055b382110fd1 in OpenWindowsPanel::SortByEditorOrder() ()
#17 0x000055b382111209 in OpenWindowsPanel::OnActiveEditorChanged(wxCommandEvent&) ()
#18 0x00007fe730eb85fe in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#19 0x00007fe730eb8ab6 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#20 0x00007fe730eb8e70 in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#21 0x00007fe730eb8f2b in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#22 0x00007fe730eb9051 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#23 0x00007fe730eb9cdd in wxEvtHandler::ProcessPendingEvents() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#24 0x00007fe730d5bb2f in wxAppConsoleBase::ProcessPendingEvents() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#25 0x00007fe7307ba579 in wxApp::DoIdle() () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk3u_core-3.1.so.5
#26 0x00007fe7307ba683 in wxapp_idle_callback () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk3u_core-3.1.so.5
#27 0x00007fe72de09e25 in g_main_dispatch (context=0x55b3840f8be0) at ../glib-2.72.0/glib/gmain.c:3417
#28 g_main_context_dispatch (context=0x55b3840f8be0) at ../glib-2.72.0/glib/gmain.c:4135
#29 0x00007fe72de0a1a8 in g_main_context_iterate (context=0x55b3840f8be0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib-2.72.0/glib/gmain.c:4211
#30 0x00007fe72de0a483 in g_main_loop_run (loop=0x55b389528e60) at ../glib-2.72.0/glib/gmain.c:4411
#31 0x00007fe73126730d in gtk_main () at /usr/x86_64-pc-linux-gnu/lib/libgtk-3.so.0
#32 0x00007fe7307d7815 in wxGUIEventLoop::DoRun() () at /usr/x86_64-pc-linux-gnu/lib/libwx_gtk3u_core-3.1.so.5
#33 0x00007fe730d90fed in wxEventLoopBase::Run() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#34 0x00007fe730d5cd0b in wxAppConsoleBase::MainLoop() () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#35 0x00007fe730ddaa66 in wxEntry(int&, wchar_t**) () at /usr/x86_64-pc-linux-gnu/lib/libwx_baseu-3.1.so.5
#36 0x000055b381e6101e in main ()
Detaching from program: /usr/x86_64-pc-linux-gnu/bin/codelite, process 72606
[Inferior 1 (process 72606) detached]
```

**Comment by eranif** [comment]
please try with this fix

**Comment by sss123next** [comment]
works now, thx.
#2961 is still present
