### ISSUE TITLE
[Bug]:  crash on "attach to process" dialog

### ISSUE THREAD

**Issue by sss123next** [eranif/codelite#3139]
### What happened?

codelite exiting with syscall exit 01 after opening "attach to process dialog" on FreeBSD system

### Version

Self compiled

### Operating system

Other

### Steps to reproduce

```text
open "attach to process" dialog from debug menu
```

### Relevant log output

```shell
Thread 40 (LWP 101179 of process 67494):
#0  0x00000008038fd99a in _nanosleep () from /lib/libc.so.7
#1  0x000000080379aa9c in ?? () from /lib/libthr.so.3
#2  0x000000080173ee57 in wxMilliSleep(unsigned long) () from /usr/local/lib/libwx_baseu-3.3.so.0
#3  0x00000008032438ba in ZombieReaperPOSIX::Entry() () from /usr/local/lib/codelite/liblibcodelite.so
#4  0x00000008017372a3 in ?? () from /usr/local/lib/libwx_baseu-3.3.so.0
#5  0x0000000803798132 in ?? () from /lib/libthr.so.3
#6  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdf3f8000

Thread 35 (LWP 101372 of process 67494):
#0  0x00000008037a69ec in ?? () from /lib/libthr.so.3
#1  0x000000080379a040 in ?? () from /lib/libthr.so.3
#2  0x00000008037a3f4b in ?? () from /lib/libthr.so.3
#3  0x0000000803727222 in std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) () from /usr/lib/libc++.so.1
#4  0x000000080334eaf4 in WorkerThread::Entry() () from /usr/local/lib/codelite/liblibcodelite.so
#5  0x00000008017372a3 in ?? () from /usr/local/lib/libwx_baseu-3.3.so.0
#6  0x0000000803798132 in ?? () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdf7fa000

Thread 29 (LWP 101264 of process 67494):
#0  0x000000080396ceba in _select () from /lib/libc.so.7
#1  0x000000080379ae52 in ?? () from /lib/libthr.so.3
#2  0x00000008031e4239 in clSocketBase::SelectRead(long) () from /usr/local/lib/codelite/liblibcodelite.so
#3  0x00000008031ea575 in clSocketServer::WaitForNewConnectionRaw(long) () from /usr/local/lib/codelite/liblibcodelite.so
#4  0x00000008031ea515 in clSocketServer::WaitForNewConnection(long) () from /usr/local/lib/codelite/liblibcodelite.so
#5  0x00000000006ffe1a in ?? ()
#6  0x00000008017372a3 in ?? () from /usr/local/lib/libwx_baseu-3.3.so.0
#7  0x0000000803798132 in ?? () from /lib/libthr.so.3
#8  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdf5f9000

Thread 28 (LWP 101223 of process 67494):
#0  0x00000008037a69ec in ?? () from /lib/libthr.so.3
#1  0x000000080379a040 in ?? () from /lib/libthr.so.3
#2  0x00000008037a3f4b in ?? () from /lib/libthr.so.3
#3  0x0000000803727222 in std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) () from /usr/lib/libc++.so.1
#4  0x000000080334eaf4 in WorkerThread::Entry() () from /usr/local/lib/codelite/liblibcodelite.so
#5  0x00000008017372a3 in ?? () from /usr/local/lib/libwx_baseu-3.3.so.0
#6  0x0000000803798132 in ?? () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdf9fb000

Thread 27 (LWP 101221 of process 67494 "pool-codelite"):
#0  0x00000008037a69ec in ?? () from /lib/libthr.so.3
#1  0x000000080379a040 in ?? () from /lib/libthr.so.3
#2  0x00000008037a3f4b in ?? () from /lib/libthr.so.3
#3  0x000000080135ed06 in g_cond_wait_until () from /usr/local/lib/libglib-2.0.so.0
#4  0x00000008012d2f96 in ?? () from /usr/local/lib/libglib-2.0.so.0
#5  0x00000008012d30f8 in g_async_queue_timeout_pop () from /usr/local/lib/libglib-2.0.so.0
#6  0x0000000801335757 in ?? () from /usr/local/lib/libglib-2.0.so.0
#7  0x0000000801334438 in ?? () from /usr/local/lib/libglib-2.0.so.0
#8  0x0000000803798132 in ?? () from /lib/libthr.so.3
#9  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdeff6000

Thread 3 (LWP 100435 of process 67494 "gmain"):
#0  0x000000080391038a in _poll () from /lib/libc.so.7
#1  0x000000080379abc6 in ?? () from /lib/libthr.so.3
#2  0x0000000801308262 in ?? () from /usr/local/lib/libglib-2.0.so.0
#3  0x0000000801308368 in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.0
#4  0x0000000801309da1 in ?? () from /usr/local/lib/libglib-2.0.so.0
#5  0x0000000801334438 in ?? () from /usr/local/lib/libglib-2.0.so.0
#6  0x0000000803798132 in ?? () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdfdfd000

Thread 2 (LWP 100315 of process 67494 "pool-spawner"):
#0  0x00000008037a69ec in ?? () from /lib/libthr.so.3
#1  0x000000080379a040 in ?? () from /lib/libthr.so.3
#2  0x00000008037a3f4b in ?? () from /lib/libthr.so.3
#3  0x000000080135eb65 in g_cond_wait () from /usr/local/lib/libglib-2.0.so.0
#4  0x00000008012d2f75 in ?? () from /usr/local/lib/libglib-2.0.so.0
#5  0x0000000801334a18 in ?? () from /usr/local/lib/libglib-2.0.so.0
#6  0x0000000801334438 in ?? () from /usr/local/lib/libglib-2.0.so.0
#7  0x0000000803798132 in ?? () from /lib/libthr.so.3
#8  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdfffe000

Thread 1 (LWP 101335 of process 67494):
#0  0x00000008007ebf7a in ?? () from /libexec/ld-elf.so.1
#1  0x00000008007da99d in ?? () from /libexec/ld-elf.so.1
#2  0x0000000000000000 in ?? ()
#0  0x00000008007ebf7a in ?? () from /libexec/ld-elf.so.1
#1  0x00000008007da99d in ?? () from /libexec/ld-elf.so.1
#2  0x0000000000000000 in ?? ()
```

**Comment by sss123next** [comment]
ok, found this one.
```
cat .codelite/codelite-stdout-stderr.log 
ld-elf.so.1: /usr/local/lib/codelite/liblibcodelite.so: Undefined symbol "kvm_openfiles"
```

i can resolve it locally, but better to add -lkvm to libcodelite.so ldflags.
